export const markets=[{symbol:'NVDA',name:'NVIDIA',price:142.87,change:2.34,color:'#a7c7dd',volume:1842000},{symbol:'AAPL',name:'Apple',price:228.52,change:.86,color:'#c2cdd3',volume:1265000},{symbol:'TSLA',name:'Tesla',price:248.50,change:-1.42,color:'#ff704b',volume:963000},{symbol:'MSFT',name:'Microsoft',price:425.76,change:1.12,color:'#8cb5d1',volume:1128000}] as const;
export const money=(n:number)=>new Intl.NumberFormat('en-US',{style:'currency',currency:'USD',maximumFractionDigits:2}).format(n);
export type Order={id:string;symbol:string;side:'buy'|'sell';kind:'limit'|'auction';qty:number;limit:number;reserve:number;roll:boolean;session:string;status:'sealed'|'filled'|'cancelled';created:string;filledPrice?:number};
export type Print={id:string;symbol:string;price:number;qty:number;time:string;session:string;proof:string};
export type Quote={id:string;symbol:string;side:'buy'|'sell';qty:number;price:number;expires:number};
export type DemoState={connected:boolean;cash:number;positions:Record<string,number>;orders:Order[];prints:Print[];quote:Quote|null;activity:{id:string;label:string;time:string}[]};
export function initialState():DemoState{return {connected:false,cash:100000,positions:{NVDA:100,AAPL:100,TSLA:100,MSFT:100},orders:[],prints:[],quote:null,activity:[]}}
const round=(v:number)=>Math.round(v*100)/100;
export function availableCash(s:DemoState){return round(s.cash-s.orders.filter(o=>o.status==='sealed'&&o.side==='buy').reduce((v,o)=>v+o.reserve,0))}
export function availableShares(s:DemoState,symbol:string){return (s.positions[symbol]||0)-s.orders.filter(o=>o.status==='sealed'&&o.side==='sell'&&o.symbol===symbol).reduce((v,o)=>v+o.qty,0)}
export function applyAction(state:DemoState,p:Record<string,unknown>,now=Date.now()):{state:DemoState;message:string}{const s=structuredClone(state);let message='';const time=new Date(now).toISOString();const id=()=>crypto.randomUUID();const positive=(v:unknown,max=1e6)=>{const n=Number(v);if(!Number.isFinite(n)||n<=0||n>max)throw new Error(`Enter a number greater than 0 and no more than ${max.toLocaleString()}.`);return n};const findMarket=()=>{const m=markets.find(m=>m.symbol===p.symbol);if(!m)throw new Error('Choose a supported market.');return m};const side=()=>{if(p.side!=='buy'&&p.side!=='sell')throw new Error('Choose buy or sell.');return p.side};const needWallet=()=>{if(!s.connected)throw new Error('Connect your wallet first.')};const ensureFunds=(symbol:string,direction:string,qty:number,value:number)=>{if(direction==='buy'&&value>availableCash(s)+.001)throw new Error('Not enough available collateral. Add funds or reduce the order.');if(direction==='sell'&&qty>availableShares(s,symbol))throw new Error('Not enough available shares for this sell order.')};
if(p.action==='connect'){s.connected=true;message='Wallet connected.'}
else if(p.action==='disconnect'){s.connected=false;message='Wallet disconnected. Your orders are saved.'}
else if(p.action==='deposit'){needWallet();const amount=round(positive(p.amount,100000));if(s.cash+amount>1e7)throw new Error('Balance limit reached.');s.cash=round(s.cash+amount);message=`${money(amount)} added to your treasury balance.`}
else if(p.action==='withdraw'){needWallet();const amount=round(positive(p.amount,100000));if(amount>availableCash(s))throw new Error('This amount is reserved or unavailable.');s.cash=round(s.cash-amount);message=`${money(amount)} withdrawn from your balance.`}
else if(p.action==='order'){needWallet();const m=findMarket();const direction=side();const qty=positive(p.qty,10000);if(!Number.isInteger(qty))throw new Error('Use a whole number of shares.');if(p.kind!=='limit'&&p.kind!=='auction')throw new Error('Choose a valid order type.');if(!['open','close','midnight'].includes(String(p.session)))throw new Error('Choose an auction session.');const limit=p.kind==='limit'?round(positive(p.limit,100000)):m.price;const reserve=round(qty*(p.kind==='auction'?m.price*1.03:limit));ensureFunds(m.symbol,direction,qty,reserve);if(s.orders.filter(o=>o.status==='sealed').length>=30)throw new Error('This terminal supports up to 30 open orders.');s.orders.unshift({id:id(),symbol:m.symbol,side:direction,kind:p.kind,qty,limit,reserve,roll:p.roll===true,session:String(p.session),status:'sealed',created:time});s.orders=s.orders.slice(0,120);message='Order sealed. Your intent is private until the call.'}
else if(p.action==='cancel'){needWallet();const o=s.orders.find(o=>o.id===p.id);if(!o||o.status!=='sealed')throw new Error('This order is no longer available to cancel.');o.status='cancelled';message='Order cancelled. Reserved collateral released.'}
else if(p.action==='clear'){needWallet();const session=String(p.session);if(!['open','close','midnight'].includes(session))throw new Error('Choose an auction session.');let fills=0;const totals:Record<string,number>={};for(const o of s.orders.filter(o=>o.status==='sealed'&&o.session===session)){const m=markets.find(m=>m.symbol===o.symbol)!;const eligible=o.kind==='auction'||(o.side==='buy'?o.limit>=m.price:o.limit<=m.price);if(eligible){o.status='filled';o.filledPrice=m.price;s.cash=round(s.cash+(o.side==='buy'?-1:1)*o.qty*m.price);s.positions[o.symbol]=(s.positions[o.symbol]||0)+(o.side==='buy'?1:-1)*o.qty;totals[o.symbol]=(totals[o.symbol]||0)+o.qty;fills++;}else if(!o.roll)o.status='cancelled';}for(const [symbol,qty] of Object.entries(totals)){s.prints.unshift({id:id(),symbol,qty,price:markets.find(m=>m.symbol===symbol)!.price,time,session,proof:`print:${id()}`})}s.prints=s.prints.slice(0,100);message=fills?`${fills} order${fills===1?'':'s'} settled in the call.`:'Call completed. Unmatched orders were rolled or cancelled according to your settings.'}
else if(p.action==='quote'){needWallet();const m=findMarket();const direction=side();const qty=positive(p.qty,10000);if(!Number.isInteger(qty)||qty<10)throw new Error('RFQ blocks require 10–10,000 whole shares.');const price=round(m.price*(direction==='buy'?1.001:0.999));ensureFunds(m.symbol,direction,qty,round(qty*price));s.quote={id:id(),symbol:m.symbol,side:direction,qty,price,expires:now+60000};message='A private quote is ready for review.'}
else if(p.action==='acceptQuote'){needWallet();const q=s.quote;if(!q||q.id!==p.id||q.expires<=now)throw new Error('This quote has expired. Request a new quote.');ensureFunds(q.symbol,q.side,q.qty,round(q.qty*q.price));s.cash=round(s.cash+(q.side==='buy'?-1:1)*q.qty*q.price);s.positions[q.symbol]=(s.positions[q.symbol]||0)+(q.side==='buy'?1:-1)*q.qty;s.orders.unshift({id:id(),symbol:q.symbol,side:q.side,kind:'limit',qty:q.qty,limit:q.price,reserve:0,roll:false,session:'rfq',status:'filled',created:time,filledPrice:q.price});s.quote=null;message='RFQ accepted. The block has settled.'}
else if(p.action==='reset'){Object.assign(s,initialState());message='Portfolio reset. Start fresh.'}
else throw new Error('This action is not supported.');
s.activity.unshift({id:id(),label:message,time});s.activity=s.activity.slice(0,30);return {state:s,message}}
export function schedule(from=new Date()){const rows:{id:string;session:string;title:string;time:string}[]=[];for(let d=0;d<9;d++){const day=new Date(Date.UTC(from.getUTCFullYear(),from.getUTCMonth(),from.getUTCDate()+d));const offset= new Intl.DateTimeFormat('en-US',{timeZone:'America/New_York',timeZoneName:'shortOffset'}).format(day).includes('GMT-4')?4:5;for(const item of [{session:'open',title:'Opening call',h:9+offset,m:30},{session:'close',title:'Closing call',h:16+offset,m:0},{session:'midnight',title:'Midnight call',h:0,m:0}]){if(item.session!=='midnight'&&[0,6].includes(day.getUTCDay()))continue;const date=new Date(day);date.setUTCHours(item.h,item.m);if(date<=from)continue;rows.push({id:`${date.toISOString()}-${item.session}`,session:item.session,title:item.title,time:date.toISOString()})}}return rows.sort((a,b)=>a.time.localeCompare(b.time)).slice(0,12)}
export function examplePrints():Print[]{return [{id:'sample-01',symbol:'NVDA',price:142.87,qty:12840,time:'2026-09-18T20:00:00Z',session:'close',proof:'sample-proof-001'},{id:'sample-02',symbol:'AAPL',price:228.52,qty:8720,time:'2026-09-18T20:00:00Z',session:'close',proof:'sample-proof-002'},{id:'sample-03',symbol:'MSFT',price:425.76,qty:4360,time:'2026-09-18T20:00:00Z',session:'close',proof:'sample-proof-003'},{id:'sample-04',symbol:'TSLA',price:248.50,qty:6950,time:'2026-09-18T13:30:00Z',session:'open',proof:'sample-proof-004'}]}
