"use client";
import {useTranslation} from "@/components/language-provider";
import {useState} from 'react';
import {ArrowUpRight,ArrowDown,ArrowRight,LockKeyhole,Clock3,ScanLine,Sunrise,Sunset,Moon,Plus,Minus} from 'lucide-react';
import {ProtocolChapter,RhythmChapter} from '@/components/chapters';
import {SiteHeader,SiteFooter} from '@/components/site-chrome';
import HeroDragon from '@/components/hero-dragon';
import {MotionSystem,ScrollStory} from '@/components/scroll-story';
import {Brand,Socials,ProtocolDialog} from '@/components/brand';
import {Accordion,AccordionItem,AccordionTrigger,AccordionContent} from '@/components/ui/accordion';
export default function Home(){const {t,locale}=useTranslation();const[protocol,setProtocol]=useState(false);return <main className="landing"><MotionSystem/><a className="skip-link" href="#protocol">{t("Skip to content")}</a><SiteHeader/>
<section className="hero hero-with-dragon"><HeroDragon/><div className="hero-topline"><span><i/>{t(" PRIVATE BY DESIGN")}</span><span>{t("BUILT ON ROBINHOOD CHAIN ↗")}</span></div><span className="hero-coordinate coord-left">{t("ONE PRICE.")}<br/>{t("ONE SHARED MOMENT.")}</span><span className="hero-coordinate coord-right">{t("PROTOCOL / 4663")}<br/>{t("SEALED CALL AUCTIONS")}</span><div className="hero-copy"><p className="eyebrow">{t("A NEW RITUAL FOR ONCHAIN MARKETS")}</p><h1 className="calligraphy">{t("Luminary")}</h1><h2>{t("The closing auction")}<br/>{t("for tokenized stocks.")}</h2><p>{t("Private orders. One clearing price. A public record.")}</p><a className="primary-action" href="/dashboard">{t("Enter the auction ")}<ArrowUpRight size={18}/></a></div><div className="hero-bottom"><a href="#protocol">{t("DISCOVER THE PROTOCOL")}</a><span>{t("SEALED INTENT. SHARED CONVICTION.")}</span><span>{t("01 — 03")}</span></div></section>
<ScrollStory id="story"/><ProtocolChapter/><RhythmChapter/>
<section className="chapter-directory section-wrap"><div className="section-intro"><div><p className="eyebrow orange">{t("EXPLORE LUMINARY")}</p><h2>{t("Every part of the story.")}</h2></div><p>{t("From private intent to a public outcome.")}<br/>{t("Go deeper into the mechanism, the technology and what comes next.")}</p></div><div className="chapter-directory-grid">{t([{href:'/protocol',n:'01',title:'The protocol',detail:'Private orders. One clearing price.',art:'torii-tides'},{href:'/technology',n:'02',title:'The technology',detail:'The architecture behind every call.',art:'midnight-dragon'},{href:'/auctions',n:'03',title:'The rhythm',detail:'Open. Close. Midnight.',art:'sakura-lake'},{href:'/vision',n:'04',title:'The vision',detail:'A foundation built to grow.',art:'waterfall-gate'}].map(c=><a href={c.href} key={c.href}><img src={`/art/${c.art}.webp`} alt={t("")} loading="eager"/><span className="eyebrow">{t(c.n)}{t(" / LUMINARY")}</span><div><h3>{t(c.title)}</h3><p>{t(c.detail)}</p></div><ArrowUpRight size={22}/></a>))}</div></section><section className="conviction"><img loading="eager" src="/art/dragon-phoenix.webp" alt={t("Silver linework of a phoenix and dragon against a deep black sky")}/><div><p className="eyebrow">{t("PRIVATE ORDERS. PUBLIC CONVICTION.")}</p><h2>{t("Move with")}<br/><em>{t("intention.")}</em></h2><p>{t("From your first sealed bid to the final print.")}<br/>{t("Experience a more deliberate market.")}</p><a className="primary-action" href="/dashboard">{t("Enter the terminal ")}<ArrowUpRight size={18}/></a></div><span className="art-caption">{t("AN OPEN RECORD. A PRIVATE PROCESS.")}</span></section>
<section className="questions section-wrap"><div><p className="eyebrow orange">{t("03 / A LITTLE MORE CLARITY")}</p><h2>{t("Before the call.")}</h2><p>{t("Good markets begin with understanding.")}</p></div><Accordion type="single" collapsible className="faq"><AccordionItem value="one"><AccordionTrigger>{t("How does a sealed auction work?")}</AccordionTrigger><AccordionContent>{t("Buyers and sellers submit private orders ahead of a scheduled call. The clearing engine finds one price that maximizes crossed volume within a reference band. Every matched order settles at that same price.")}</AccordionContent></AccordionItem><AccordionItem value="two"><AccordionTrigger>{t("What happens to an unfilled order?")}</AccordionTrigger><AccordionContent>{t("You choose. Eligible unfilled orders can roll into the next auction or cancel after the call. Your reserved collateral is released when an order is cancelled.")}</AccordionContent></AccordionItem><AccordionItem value="three"><AccordionTrigger>{t("What is treasury settlement?")}</AccordionTrigger><AccordionContent>{t("Luminary is designed to settle in tokenized treasuries. Resting collateral can accrue the underlying fund’s NAV yield while waiting. Yield is variable and is never guaranteed.")}</AccordionContent></AccordionItem><AccordionItem value="four"><AccordionTrigger>{t("Can I trade between auctions?")}</AccordionTrigger><AccordionContent>{t("RFQ enables private, two-party block trades between scheduled calls. Request a quote, review the terms, and accept before it expires. Try the complete flow in the terminal.")}</AccordionContent></AccordionItem></Accordion></section>
<SiteFooter/><ProtocolDialog open={protocol} onClose={()=>setProtocol(false)}/></main>}
