"use client";
import {useTranslation} from "@/components/language-provider";
import {useState} from 'react';
import {Send,ArrowUpRight,Orbit} from 'lucide-react';
import {Dialog,DialogContent,DialogTitle,DialogDescription} from '@/components/ui/dialog';
import {Button} from '@/components/ui/button';
export function Brand({compact=false,tagline}:{compact?:boolean;tagline?:string}){const {t,locale}=useTranslation();return <a className="brand" href="/" aria-label={t("Luminary home")}><img src="/art/emblem.webp" alt={t("")}/>{t(!compact&&<span className="brand-type"><span>{t("LUMINARY")}</span>{t(tagline&&<small>{t(tagline)}</small>)}</span>)}</a>}
export function Socials(){const {t,locale}=useTranslation();const[social,setSocial]=useState('');return <><div className="socials"><a href="https://x.com/LuminariesRH" target="_blank" rel="noopener noreferrer" aria-label={t("X community")}><svg viewBox="0 0 24 24" width="18" height="18" fill="currentColor" aria-hidden="true"><path d="M18.9 2H22l-6.8 7.8L23.2 22h-6.3l-4.9-7.4L5.5 22H2.3l8.2-9.4L.8 2h6.4l4.4 6.7L18.9 2zm-1.1 18h1.7L6.2 3.9H4.4L17.8 20z"/></svg></a><button aria-label={t("GitHub repository")} onClick={()=>setSocial('GitHub')}><svg viewBox="0 0 24 24" width="19" height="19" fill="currentColor" aria-hidden="true"><path d="M12 .7a11.5 11.5 0 0 0-3.64 22.4c.58.1.79-.25.79-.55v-2.14c-3.2.7-3.87-1.36-3.87-1.36-.52-1.33-1.28-1.68-1.28-1.68-1.05-.71.08-.7.08-.7 1.16.09 1.77 1.19 1.77 1.19 1.03 1.76 2.7 1.25 3.36.96.1-.75.4-1.25.73-1.54-2.55-.29-5.23-1.28-5.23-5.68 0-1.25.45-2.27 1.18-3.07-.12-.29-.51-1.46.11-3.05 0 0 .97-.31 3.16 1.18a10.9 10.9 0 0 1 5.76 0c2.19-1.49 3.15-1.18 3.15-1.18.63 1.59.24 2.76.12 3.05.73.8 1.18 1.82 1.18 3.07 0 4.41-2.69 5.39-5.25 5.67.41.36.78 1.06.78 2.14v3.14c0 .31.21.66.8.55A11.5 11.5 0 0 0 12 .7z"/></svg></button><a href="https://t.me/LuminaryOnRH" target="_blank" rel="noopener noreferrer" aria-label={t("Telegram community")}><Send size={19}/></a></div><Dialog open={!!social} onOpenChange={open=>!open&&setSocial('')}><DialogContent className="coming-soon"><img src="/art/emblem.webp" alt={t("Luminary")}/><p className="eyebrow orange">{t("LUMINARY / ")}{t(social.toUpperCase())}</p><DialogTitle>{t("Coming soon")}</DialogTitle><DialogDescription>{t(`Our ${social} channel is taking shape.`)}<br/>{t("The next chapter is just ahead.")}</DialogDescription><Button onClick={()=>setSocial('')}>{t("Back to Luminary ")}<ArrowUpRight/></Button></DialogContent></Dialog> </>}
export function ProtocolDialog({open,onClose}:{open:boolean,onClose:()=>void}){const {t,locale}=useTranslation();return <Dialog open={open} onOpenChange={x=>!x&&onClose()}><DialogContent className="protocol-dialog"><p className="eyebrow orange">{t("THE LUMINARY PROTOCOL")}</p><DialogTitle>{t("Private intent. Verifiable outcomes.")}</DialogTitle><DialogDescription>{t("From the Luminary Overview, Backend and Expansion documents.")}</DialogDescription><div className="protocol-body"><h3><Orbit size={17}/>{t(" Sealed call auctions")}</h3><p>{t("Orders are collected privately before a scheduled call. A uniform clearing price maximizes crossed volume inside the reference-price band. Orders can specify a limit or accept the auction price.")}</p><h3>{t("Treasury settlement")}</h3><p>{t("Tokenized treasury collateral settles the auction. Resting collateral can earn its underlying NAV yield; returns vary and are not guaranteed.")}</p><h3>{t("Public prints, private orders")}</h3><p>{t("The clearing price and crossed volume become public. Identities and individual orders remain private. Solvency proofs and view keys support verification.")}</p><h3>{t("Between the calls")}</h3><p>{t("RFQ supports privately negotiated two-party blocks. Issuer-requested auctions can use NAV as the reference.")}</p><p className="disclosure">{t("The live protocol is intended for eligible non-US participants, subject to jurisdiction and asset restrictions. Assets shown here are illustrative and no real settlement occurs.")}</p></div></DialogContent></Dialog>}
