"use client";
import {useTranslation} from "@/components/language-provider";
import {useEffect,useRef,useState} from 'react';
import {ArrowUpRight,ArrowRight,LockKeyhole,Layers,ScanLine,Sunrise,Sunset,Moon} from 'lucide-react';
const clamp=(n:number)=>Math.max(0,Math.min(1,n));
const ease=(n:number)=>{const x=clamp(n);return x*x*(3-2*x)};
function useChapter(onFrame:(progress:number)=>void){const section=useRef<HTMLElement>(null);const cb=useRef(onFrame);cb.current=onFrame;useEffect(()=>{const el=section.current;if(!el)return;let frame=0;let value=-1;let active=false;const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;el.dataset.reduced=String(reduced);if(reduced){el.querySelectorAll('[aria-hidden=true]').forEach(node=>node.removeAttribute('aria-hidden'));return}const render=()=>{if(!active)return;const nav=innerWidth<700?74:88;const rect=el.getBoundingClientRect();const target=clamp(-(rect.top-nav)/(rect.height-(innerHeight-nav)));value=value<0?target:value+(target-value)*.16;cb.current(value);frame=requestAnimationFrame(render)};const io=new IntersectionObserver(([entry])=>{active=entry.isIntersecting;if(active)frame=requestAnimationFrame(render);else cancelAnimationFrame(frame)},{rootMargin:'200px'});io.observe(el);return()=>{active=false;cancelAnimationFrame(frame);io.disconnect()}},[]);return section}
const protocolSteps=[{n:'01',title:'Seal your\nintent.',label:'PRIVATE COLLECTION',image:'sakura-lake',icon:LockKeyhole,text:'Place a limit order or accept the auction price. Your order stays private while it waits for the call.',detail:'LIMIT OR AUCTION PRICE',caption:'THE QUIET BEFORE THE CALL'},{n:'02',title:'Meet at\none price.',label:'UNIFORM CLEARING',image:'torii-tides',icon:Layers,text:'At the scheduled call, one reference-bounded price maximizes crossed volume. Every matched order meets at that price.',detail:'ONE CALL. ONE CLEARING PRICE.',caption:'A SHARED MOMENT OF CLARITY'},{n:'03',title:'Let the\nprint speak.',label:'PUBLIC OUTCOME',image:'waterfall-gate',icon:ScanLine,text:'The clearing price and crossed volume become public. Individual orders and identities remain private.',detail:'PRICE + VOLUME. NOTHING MORE.',caption:'PRIVATE INTENT. OPEN OUTCOMES.'}];
export function ProtocolChapter({id='protocol'}:{id?:string}){const {t,locale}=useTranslation();const track=useRef<HTMLDivElement>(null);const panel=useRef<HTMLDivElement>(null);const[active,setActive]=useState(0);const current=useRef(0);const section=useChapter(p=>{if(track.current)track.current.style.transform=`translate3d(${-p*66.6667}%,0,0)`;panel.current?.style.setProperty('--chapter-progress',String(p));const index=Math.min(2,Math.round(p*2));if(index!==current.current){current.current=index;setActive(index)}});return <section ref={section} id={id} className="protocol-chapter scroll-chapter" aria-label={t("The protocol: seal, clear, publish")}><div ref={panel} className="chapter-sticky protocol-sticky"><div className="chapter-top"><span>{t("02 / THE PROTOCOL")}</span><span>{t("SEALED → CLEARED → PUBLISHED")}</span></div><div className="protocol-narrative"><p className="eyebrow">{t("FROM INTENT TO PRINT")}</p><div className="protocol-stage-copy" aria-live="polite">{t(protocolSteps.map((s,i)=><article key={s.n} className={active===i?'current':''} aria-hidden={active!==i}><span className="protocol-big-number">{t(s.n)}</span><h2>{t(s.title)}</h2><p>{t(s.text)}</p></article>))}</div><a href="/protocol" className="chapter-link">{t("Inside the protocol ")}<ArrowUpRight size={17}/></a></div><div className="protocol-film-window"><div ref={track} className="protocol-film-track">{t(protocolSteps.map((s,i)=><figure key={s.n} className="protocol-film-panel"><img src={`/art/${s.image}.webp`} alt={t(s.caption)} loading="eager"/><div className="protocol-film-shade"/><div className="protocol-film-data"><s.icon size={24}/><span>{t(s.label)}</span><strong>{t(s.n)}</strong></div><figcaption><span>{t(s.caption)}</span><span>{t("LUMINARY / ")}{t(s.n)}</span></figcaption></figure>))}</div></div><div className="protocol-step-rail">{t(protocolSteps.map((s,i)=><div key={s.n} data-active={active===i}><span>{t(s.n)}</span><strong>{t(s.label)}</strong>{t(i<2&&<ArrowRight size={13}/>)}</div>))}</div><div className="chapter-scroll-progress"/></div></section>}
export {default as RhythmChapter} from '@/components/rhythm-slipstream';
