"use client";
import {useTranslation} from "@/components/language-provider";
import {useEffect,useRef,useState} from 'react';
import {Pause,Play,RotateCw} from 'lucide-react';
const MODEL='d942a0d167594169b3f037f562458d38';
type ViewerAPI={start:()=>void;stop:()=>void;addEventListener:(event:string,callback:()=>void)=>void;setBackground:(options:{color:number[]})=>void;setUserInteraction:(enabled:boolean)=>void;setCycleMode:(mode:string)=>void;setSpeed:(speed:number)=>void;play:(callback?:(error:unknown)=>void)=>void;pause:(callback?:(error:unknown)=>void)=>void};
type ViewerConstructor=new (version:string,iframe:HTMLIFrameElement)=>{init:(model:string,options:Record<string,unknown>)=>void};
export default function HeroDragon(){const {t,locale}=useTranslation();const frame=useRef<HTMLIFrameElement>(null);const api=useRef<ViewerAPI|null>(null);const[status,setStatus]=useState<'loading'|'ready'|'error'>('loading');const[playing,setPlaying]=useState(true);const[retry,setRetry]=useState(0);
useEffect(()=>{let live=true;let started=false;let viewerReady=false;setStatus('loading');const reduced=matchMedia('(prefers-reduced-motion: reduce)').matches;setPlaying(!reduced);const timer=setTimeout(()=>{if(live&&!viewerReady)setStatus('error')},45000);const initialize=()=>{const Constructor=(window as Window&{Sketchfab?:ViewerConstructor}).Sketchfab;if(!live||!frame.current||!Constructor||started)return;started=true;new Constructor('1.12.1',frame.current).init(MODEL,{autostart:1,preload:1,animation_autoplay:reduced?0:1,autospin:0,camera:1,ui_theme:'dark',dnt:1,annotations_visible:0,annotation_tooltip_visible:0,ui_infos:0,ui_controls:0,ui_watermark:0,ui_hint:0,ui_stop:0,ui_help:0,ui_settings:0,ui_fullscreen:0,ui_vr:0,ui_ar:0,ui_inspector:0,ui_annotations:0,ui_animations:0,ui_general_controls:0,scrollwheel:0,success(viewer:ViewerAPI){if(!live)return;api.current=viewer;viewer.addEventListener('viewerready',()=>{if(!live)return;viewerReady=true;clearTimeout(timer);viewer.setBackground({color:[.018,.027,.034]});viewer.setUserInteraction(true);viewer.setCycleMode('loopOne');viewer.setSpeed(.7);if(reduced)viewer.pause();else viewer.play();setStatus('ready')});viewer.start()},error(){if(live)setStatus('error')}})};let script=document.querySelector<HTMLScriptElement>('script[data-luminary-sketchfab]');const fail=()=>{if(live)setStatus('error')};if((window as Window&{Sketchfab?:ViewerConstructor}).Sketchfab)initialize();else{if(script&&retry>0){script.remove();script=null}if(!script){script=document.createElement('script');script.src='https://static.sketchfab.com/api/sketchfab-viewer-1.12.1.js';script.async=true;script.dataset.luminarySketchfab='true';document.head.appendChild(script)}script.addEventListener('load',initialize);script.addEventListener('error',fail)}return()=>{live=false;clearTimeout(timer);script?.removeEventListener('load',initialize);script?.removeEventListener('error',fail);api.current?.stop();api.current=null}},[retry]);
function toggle(){const viewer=api.current;if(!viewer)return;const next=!playing;const callback=(error:unknown)=>{if(!error)setPlaying(next)};if(next)viewer.play(callback);else viewer.pause(callback)}
return <><div className={`dragon-backdrop dragon-${status}`}><iframe ref={frame} title={t("Luminary animated dragon")} allow="autoplay; fullscreen; xr-spatial-tracking" allowFullScreen referrerPolicy="strict-origin-when-cross-origin"/><div className="dragon-shade"/></div><div className="dragon-playback">{t(status==='ready'?<button onClick={toggle} aria-label={t(playing?'Pause dragon animation':'Play dragon animation')}>{t(playing?<Pause size={13}/>:<Play size={13}/>)}<span>{t(playing?'PAUSE SCENE':'PLAY SCENE')}</span></button>:status==='error'?<button onClick={()=>setRetry(v=>v+1)}><RotateCw size={13}/><span>{t("RELOAD 3D SCENE")}</span></button>:<span className="dragon-loading"><i/>{t(" LOADING 3D SCENE")}</span>)}</div></>}
