"use client";
import {useTranslation} from "@/components/language-provider";
import {SiteHeader,SiteFooter} from '@/components/site-chrome';
import {ArrowUpRight,FileText} from 'lucide-react';
type Section={title:string;paragraphs:string[]};
const documents:Record<string,{title:string;description:string;sections:Section[]}>= {
terms:{title:'Terms of use',description:'The scope and boundaries of the Luminary website.',sections:[
{title:'About this draft',paragraphs:['This draft reflects the Luminary Overview, Backend and Expansion documents and the current website. It is not the final set of terms for an operating trading venue. The legal operator, registered address, contact channel, governing law and dispute terms have not been supplied and must be completed before a public live launch.']},
{title:'Not yet a live trading service',paragraphs:['This site explains the proposed Luminary protocol and lets you explore the auction, RFQ and treasury workflows. Balances and assets shown here have no monetary value. Connecting a wallet in the interface does not connect an external wallet, deposit money or create a securities account.','Order submission, cancellation, settlement and print records on this site do not execute a blockchain transaction or trade a real security. The clearing flow uses fixed sample reference prices and is not the production volume-maximizing clearing engine.']},
{title:'Information and planned functionality',paragraphs:['Product descriptions summarize the supplied documents. The intended protocol uses scheduled sealed auctions, reference-bounded uniform clearing, tokenized treasury settlement and public price-and-volume prints. These descriptions are design objectives rather than a representation that a live service, security audit, regulatory approval or production proof system exists.','Roadmap and expansion pages describe planned work. The sequence, scope and timing may change. No launch date, token distribution, fee entitlement or return is promised by this site.']},
{title:'Eligibility and asset boundaries',paragraphs:['The product documents describe securities-form real-world assets, intended for eligible non-US participants in permitted jurisdictions. Any live service would require jurisdiction, participant and asset eligibility controls. This site does not perform those checks or establish that a visitor is eligible for a future service.','Do not rely on access to this website as permission to purchase, sell, hold or transfer an asset in any jurisdiction. Separate live-service terms and issuer restrictions would apply if those services launch.']},
{title:'Use of this website',paragraphs:['Use the site for evaluating and understanding the product. Do not submit real private keys, seed phrases, identity documents or confidential account information. The interface does not request them.','Do not attempt to access another visitor’s local portfolio, compromise the site, interfere with availability or misrepresent illustrative records as real transactions or cryptographic proofs. Records here can be reset and should not be relied on as a permanent financial record.']},
{title:'Financial information and outcomes',paragraphs:['This website is informational and does not provide personalized investment, legal or tax advice. It is not an offer or solicitation to purchase securities or a guarantee of execution, price quality, liquidity or yield.','Treasury yield in the product documents refers to underlying published NAV accrual. It is variable. No investment return accrues on this site. Read the Risk & Eligibility page alongside these terms.']},
{title:'Artwork and third-party services',paragraphs:['The website includes Luminary branding and supplied artwork. The animated hero model, “Animated Realistic Lowpoly Chinese Dragon,” is embedded from Sketchfab and credited to Cassana XR. Rights in third-party materials remain with their respective owners.','An embedded service or external link can be unavailable or operate under its own terms and privacy policy. Naming Robinhood Chain or another technology describes the proposed integration; it does not by itself establish endorsement or affiliation.']},
{title:'Before live launch',paragraphs:['These draft terms require review and completion by the responsible operator and qualified counsel. In addition to entity and jurisdiction details, live-service disclosures must address actual custody, fees, execution rules, complaints, suspension, liability and any applicable regulated-service obligations. This draft does not invent those details or represent that they have been approved.']}
]},
privacy:{title:'Privacy notice',description:'What this website stores and how its visible features use data.',sections:[
{title:'About this draft',paragraphs:['This notice describes the current website implementation. The supplied Luminary documents describe intended protocol privacy but do not identify the final legal controller, privacy contact or complete live-service data practices. Those details and any required jurisdiction-specific disclosures remain to be finalized before public launch.']},
{title:'Portfolio information',paragraphs:['This site stores balances, holdings, orders, RFQ quotes, auction results and recent activity in this browser and device. Portfolio records are not sent to a server.','The site does not ask for a name, email address, wallet address, government identification or payment details. “Connect wallet” changes the interface state; it does not access a real wallet. The hosting platform may separately handle sign-in and access to a privately published site.']},
{title:'Browser storage',paragraphs:['The site uses the IndexedDB database luminary-portfolio. Records remain on this site and device until reset or until you clear site data. They do not synchronize across devices.','The sidebar_state cookie remembers navigation preferences for up to seven days. The luminary_language local storage preference remembers your language on this device. Blocking browser storage may prevent portfolio persistence. Fonts and artwork are served with the website.']},
{title:'Why this information is stored',paragraphs:['The saved portfolio lets order, cancellation, RFQ and treasury actions work across page reloads. Checks use it to prevent overspending of collateral, duplicate quote acceptance and conflicting portfolio updates.','This implementation does not add its own advertising pixels or marketing analytics. Hosting and third-party services may process technical connection information under their own policies. A private product order is not the same as anonymous website use.']},
{title:'The animated Sketchfab model',paragraphs:['The hero loads a Sketchfab viewer and its JavaScript to display the animated Chinese dragon. Connecting to that service can expose technical information, such as an IP address, browser details and request metadata, to the provider. The embed requests Sketchfab’s do-not-track option; that setting is not a promise that no provider data processing occurs.','Sketchfab operates under its own privacy policy. The external privacy link opens Sketchfab’s site. You can block third-party content using your browser, although the animated scene may then be unavailable.']},
{title:'Retention and your controls',paragraphs:['Local portfolio records remain until you reset the portfolio or clear site data in your browser. This edition has no server portfolio records or automatic retention schedule.','Resetting clears active orders, quotes and prints and restores the starting portfolio. Disconnecting the wallet preserves local orders. Clearing site data deletes the local portfolio. These actions do not erase hosting logs or third-party records.']},
{title:'Protocol privacy and its limits',paragraphs:['The Luminary specifications distinguish sealed individual orders and identities from public auction clearing prices and crossed volumes. They also refer to solvency proofs and view keys. These are intended protocol properties, not a statement that this prototype implements cryptographic privacy.','This edition stores its records in browser IndexedDB. Anyone with access to this browser profile may access those records. Do not provide sensitive financial or personal information here.']},
{title:'Operator details and requests',paragraphs:['A verified legal operator name, postal address, privacy contact, retention schedule and applicable rights-request process are not provided in the source documents. They must be supplied and reviewed before this draft becomes a live-service privacy notice. No contact address or jurisdiction has been invented here.']}
]},
risks:{title:'Risk & eligibility',description:'Private orders do not remove the risks of markets, assets or software.',sections:[
{title:'Current experience',paragraphs:['Prices, assets, collateral, fills and proof records on this site are illustrative. There is no real custody, asset transfer, investment return or blockchain settlement. The following points describe boundaries and risks relevant to the proposed product, not an assertion that the live service is available.']},
{title:'Securities and jurisdiction',paragraphs:['The product overview expressly describes securities-form real-world assets and a non-US, jurisdiction-gated participant base. Availability would depend on participant eligibility, issuer terms, supported assets and applicable restrictions.','The website does not determine legal eligibility. Access to this site is not authorization to transact, and references to tokenized stocks do not establish the exact ownership or shareholder rights of a future instrument. Those would need to be explained in the relevant issuer documents.']},
{title:'Price, liquidity and execution',paragraphs:['An auction aims to bring eligible buyers and sellers together at one clearing price. It does not guarantee enough opposing interest, a full fill or an economically favorable outcome. A limit order may remain unfilled; an at-auction order accepts the eventual clearing price subject to the configured band.','The intended reference band constrains the auction price relative to an external stock reference or fund NAV. It cannot ensure that a reference is timely, error-free or continuously available. Market dislocations and underlying asset events can affect token prices and liquidity.']},
{title:'Treasury collateral and yield',paragraphs:['The design uses tokenized treasuries as settlement collateral. Such instruments can carry issuer, custody, redemption, liquidity, valuation and market risks. A tokenized treasury should not be assumed to be equivalent to a cash deposit or protected bank account.','Published NAV accrual can vary, and the documents do not establish a guaranteed rate or return. This site displays balances without accruing real yield. Fees, redemption terms and issuer documentation for any live collateral asset would require separate disclosure.']},
{title:'Timing and corporate actions',paragraphs:['The intended schedule follows underlying-market open and close, plus 00:00 UTC. The backend specification includes daylight saving and holiday handling, NAV calls and ex-date pauses. A calendar does not eliminate outages, delayed calls or corporate-action complexity.','The displayed schedule accounts for New York daylight saving and weekends but not exchange holidays, ex-dates, issuer-specific events or production chain availability. Do not use it as a live trading schedule.']},
{title:'Technology, proofs and privacy',paragraphs:['Smart contracts, reference feeds, clearing logic, schedulers, proof systems and chain infrastructure may fail or behave unexpectedly. The supplied specification is not a completed security audit or an assurance of production readiness.','The documents describe a possible signed clearing digest before a full proof upgrade. A signature and a cryptographic auction proof provide different assurances. The proof records shown here are illustrative only.','Private orders and public prints are distinct design goals. Privacy can still be affected by implementation flaws, metadata, compromised devices or authorized view-key access. Do not assume anonymity from a sealed-order label.']},
{title:'RFQ and expansion',paragraphs:['RFQ blocks depend on counterparties, valid quotes and execution conditions. This site uses a fixed spread and a quote expiry, not live counterparties or market-making liquidity.','Issuer launches, index rebalances, Arc and FX auctions, calendar data products, agent mandates and derivative settlement references are planned directions. They may change, be deferred or not launch. Nothing on the roadmap guarantees adoption or economic returns.']},
{title:'Review before any live use',paragraphs:['A live service would need finalized legal and issuer disclosures, eligibility procedures, security information, fees, execution rules and support channels. This draft should be reviewed by the responsible operator and qualified legal counsel before launch. It does not certify compliance or replace those materials.']}
]}
};
export default function LegalPage({kind}:{kind:'terms'|'privacy'|'risks'}){const {t,locale}=useTranslation();const doc=documents[kind];return <main className="landing legal-page"><SiteHeader/><section className="legal-heading section-wrap"><div><p className="eyebrow orange">{t("LUMINARY / LEGAL")}</p><h1>{t(doc.title)}</h1><p>{t(doc.description)}</p></div><div className="legal-draft"><FileText size={19}/><span>{t("DRAFT FOR REVIEW")}<br/><small>{t("Prepared 21 September 2026")}</small></span></div></section><div className="legal-layout"><aside><span>{t("ON THIS PAGE")}</span>{t(doc.sections.map((s,i)=><a key={s.title} href={`#section-${i+1}`}>{t(String(i+1).padStart(2,'0'))}{t(" / ")}{t(s.title)}</a>))}<div className="legal-related"><a href="/legal/terms" aria-current={kind==='terms'?'page':undefined}>{t("Terms of use ")}<ArrowUpRight size={12}/></a><a href="/legal/privacy" aria-current={kind==='privacy'?'page':undefined}>{t("Privacy notice ")}<ArrowUpRight size={12}/></a><a href="/legal/risks" aria-current={kind==='risks'?'page':undefined}>{t("Risk & eligibility ")}<ArrowUpRight size={12}/></a></div></aside><article><div className="legal-notice">{t("These pages distinguish the current website from the planned protocol. Entity, jurisdiction and contact details require completion before live launch.")}</div>{t(doc.sections.map((s,i)=><section id={`section-${i+1}`} key={s.title}><p className="eyebrow orange">{t(String(i+1).padStart(2,'0'))}</p><h2>{t(s.title)}</h2>{t(s.paragraphs.map(p=><p key={p}>{t(p)}</p>))}{t(kind==='privacy'&&i===4&&<a className="legal-external" href="https://sketchfab.com/privacy" target="_blank" rel="noopener noreferrer">{t("Sketchfab privacy policy ")}<ArrowUpRight size={14}/></a>)}</section>))}<div className="legal-source">{t("Source basis: Luminary Overview, Luminary Backend and Luminary Expansion; plus the current website’s implemented data and behavior.")}</div></article></div><SiteFooter/></main>}
