"use client";
import {useEffect,useRef,useState,type CSSProperties,type PointerEvent} from 'react';
import {ArrowLeft,ArrowRight,ArrowUpRight,Pause,Play} from 'lucide-react';
import {useTranslation} from '@/components/language-provider';
import {beltPose,nearestSessionOffset,slipstreamConfig as config} from '@/lib/slipstream-motion';
const sessions=[
 {name:'Open.',meta:'AT THE UNDERLYING MARKET OPEN',image:'landscape',caption:'Start together. Gather liquidity as the underlying market begins its day.'},
 {name:'Close.',meta:'AT THE UNDERLYING MARKET CLOSE',image:'dragon-waves',caption:'End with clarity. Meet at one clearing price as the trading session closes.'},
 {name:'Midnight.',meta:'00:00 UTC · A GLOBAL CHECKPOINT',image:'dragon-phoenix',caption:'A new moment between market sessions. A daily call for a world that keeps moving.'},
];
const cardArt=['sakura-lake','torii-tides','midnight-dragon','mountain-tide','swallow-orbits','waterfall-gate'];
const cards=cardArt.map((image,i)=>({...sessions[i%sessions.length],image}));
export default function RhythmSlipstream({id='rhythm'}:{id?:string}){
 const{t}=useTranslation();const section=useRef<HTMLElement>(null),stage=useRef<HTMLDivElement>(null),cardRefs=useRef<(HTMLElement|null)[]>([]);
 const motion=useRef({pos:0,velocity:0,target:null as number|null,step:230*1.3,dragging:false,pressed:false,startX:0,startY:0,lastX:0,hover:null as HTMLElement|null,focused:false,paused:false,reduced:false});
 const [active,setActive]=useState(0),[paused,setPaused]=useState(false),[reduced,setReduced]=useState(false);
 const wake=useRef<()=>void>(()=>{});
 useEffect(()=>{const el=section.current,pane=stage.current;if(!el||!pane)return;const m=motion.current,media=matchMedia('(prefers-reduced-motion: reduce)');let frame=0,visible=false,last=0,current=-1;
 const place=()=>{let nearest=0,distance=Infinity;cardRefs.current.forEach((card,i)=>{if(!card)return;const pose=beltPose(i,m.pos,m.step);card.style.transform=pose.transform;card.style.opacity=String(pose.opacity);card.style.visibility=pose.opacity<.008?'hidden':'visible';if(Math.abs(pose.x)<distance){distance=Math.abs(pose.x);nearest=i}});const next=nearest%sessions.length;if(next!==current){current=next;setActive(next)}};
 const tick=(now:number)=>{frame=0;if(!visible||document.hidden||m.reduced)return;const dt=last?Math.min(2,(now-last)/16.667):1;last=now;
 if(m.target!==null){m.pos+=(m.target-m.pos)*(1-Math.pow(.84,dt));if(Math.abs(m.target-m.pos)<.1){m.pos=m.target;m.target=null}}
 else if(!m.dragging){if(!m.hover){m.pos+=m.velocity*dt;if(!m.paused&&!m.focused)m.pos-=config.autoScroll*dt}m.velocity*=Math.pow(config.damp,dt);if(Math.abs(m.velocity)<.005)m.velocity=0}
 if(m.target===null)m.pos=((m.pos%(m.step*config.slots))+m.step*config.slots)%(m.step*config.slots);
 place();const moving=m.target!==null||m.dragging||Math.abs(m.velocity)>.005||(!m.paused&&!m.focused&&!m.hover);if(moving)frame=requestAnimationFrame(tick)};
 const request=()=>{if(!frame&&visible&&!document.hidden&&!m.reduced){last=0;frame=requestAnimationFrame(tick)}};wake.current=request;
 const layout=()=>{const previousStep=m.step;const width=Math.min(250,Math.max(168,pane.clientWidth*.16));m.step=width*(1+config.spacing);m.pos=m.pos/previousStep*m.step;m.target=null;pane.style.setProperty('--slip-cw',`${width}px`);pane.style.setProperty('--slip-ch',`${width*config.cardRatio}px`);pane.style.perspective=`${Math.max(800,pane.clientWidth*.9)}px`;m.reduced=media.matches;setReduced(media.matches);if(m.reduced){cancelAnimationFrame(frame);frame=0}else place();request()};
 const observer=new IntersectionObserver(([entry])=>{visible=entry.isIntersecting;if(visible)request();else{cancelAnimationFrame(frame);frame=0;last=0}},{rootMargin:'100px'});observer.observe(el);const visibility=()=>{if(document.hidden){cancelAnimationFrame(frame);frame=0}else request()};layout();window.addEventListener('resize',layout);media.addEventListener('change',layout);document.addEventListener('visibilitychange',visibility);
 return()=>{cancelAnimationFrame(frame);observer.disconnect();window.removeEventListener('resize',layout);media.removeEventListener('change',layout);document.removeEventListener('visibilitychange',visibility);wake.current=()=>{}};
 },[]);
 function hover(card:HTMLElement|null){const m=motion.current;if(card===m.hover)return;m.hover?.classList.remove('is-active');m.hover=card;card?.classList.add('is-active');wake.current()}
 function pointDown(e:PointerEvent<HTMLDivElement>){if(e.button!==0||motion.current.reduced)return;const m=motion.current;m.pressed=true;m.startX=m.lastX=e.clientX;m.startY=e.clientY;m.velocity=0;m.target=null;hover(null);if(e.pointerType==='mouse'){m.dragging=true;e.currentTarget.setPointerCapture(e.pointerId);e.currentTarget.classList.add('is-dragging')}wake.current()}
 function pointMove(e:PointerEvent<HTMLDivElement>){const m=motion.current;if(m.reduced)return;if(m.pressed&&!m.dragging&&Math.abs(e.clientX-m.startX)>7&&Math.abs(e.clientX-m.startX)>Math.abs(e.clientY-m.startY)){m.dragging=true;e.currentTarget.setPointerCapture(e.pointerId);e.currentTarget.classList.add('is-dragging')}
 if(m.dragging){const delta=(e.clientX-m.lastX)*config.drag;m.pos+=delta;m.velocity=delta;m.lastX=e.clientX;wake.current()}else if(!m.pressed&&e.pointerType==='mouse'){const hit=document.elementFromPoint(e.clientX,e.clientY)?.closest<HTMLElement>('.rhythm-slip-card')||null;hover(hit&&section.current?.contains(hit)?hit:null)}}
 function pointEnd(e:PointerEvent<HTMLDivElement>){const m=motion.current;m.pressed=false;m.dragging=false;e.currentTarget.classList.remove('is-dragging');if(e.currentTarget.hasPointerCapture(e.pointerId))e.currentTarget.releasePointerCapture(e.pointerId);wake.current()}
 function move(direction:number){const m=motion.current;hover(null);if(m.reduced){const next=(active+direction+sessions.length)%sessions.length;setActive(next);cardRefs.current[next]?.scrollIntoView({block:'nearest',behavior:'auto'});return}m.velocity=0;m.target=(m.target??m.pos)-direction*m.step;wake.current()}
 function choose(index:number){const m=motion.current;hover(null);if(m.reduced){setActive(index);cardRefs.current[index]?.scrollIntoView({block:'nearest',behavior:'auto'});return}m.velocity=0;m.target=m.pos+nearestSessionOffset(index,m.pos,m.step);wake.current()}
 return <section ref={section} id={id} className="rhythm-slipstream" aria-label={t('The rhythm: opening, closing and midnight auctions')} onFocusCapture={()=>{motion.current.focused=true}} onBlurCapture={e=>{if(!e.currentTarget.contains(e.relatedTarget as Node|null)){motion.current.focused=false;wake.current()}}}><div className="slipstream-topline"><span>{t('03 / THE RHYTHM')}</span><a href="/auctions">{t('Explore the rhythm')}<ArrowUpRight size={14}/></a></div><div className="slipstream-heading"><p className="eyebrow">{t('THREE CALLS. ONE DAILY RITUAL.')}</p><h2>{t('A shared')} <em className="calligraphy">{t('rhythm.')}</em></h2><p>{t('Open. Close. Midnight. Know your next moment.')}</p></div><div ref={stage} className="slipstream-stage" role="region" tabIndex={0} aria-label={t('Auction sessions. Drag horizontally or use the left and right arrow keys.')} onPointerDown={pointDown} onPointerMove={pointMove} onPointerUp={pointEnd} onPointerCancel={pointEnd} onLostPointerCapture={pointEnd} onPointerLeave={()=>hover(null)} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();move(e.key==='ArrowRight'?1:-1)}}}><div className="slipstream-belt">{cards.map((c,i)=><article className="rhythm-slip-card" key={i} ref={el=>{cardRefs.current[i]=el}} aria-hidden={i>=3} style={{transform:beltPose(i,0,299).transform,opacity:beltPose(i,0,299).opacity} as CSSProperties}><div className="slip-card-inner"><img src={`/art/${c.image}.webp`} alt="" draggable={false} loading="eager"/><div className="slip-card-scrim"/><div className="slip-card-top">{String(i%3+1).padStart(2,'0')} / LUMINARY</div><div className="slip-card-foot"><h3 className="calligraphy">{t(c.name)}</h3><p>{t(c.meta)}</p></div></div></article>)}</div></div><div className="slipstream-vignette"/><div className="slipstream-bottom"><div className="slipstream-controls"><button onClick={()=>move(-1)} aria-label={t('Previous auction session')}><ArrowLeft size={18}/></button><div className="slipstream-session-buttons">{sessions.map((c,i)=><button key={c.name} aria-pressed={active===i} onClick={()=>choose(i)}>{t(c.name)}</button>)}</div><button onClick={()=>move(1)} aria-label={t('Next auction session')}><ArrowRight size={18}/></button>{!reduced&&<button aria-label={t(paused?'Resume card motion':'Pause card motion')} aria-pressed={paused} onClick={()=>{motion.current.paused=!paused;setPaused(!paused);wake.current()}}>{paused?<Play size={15}/>:<Pause size={15}/>}</button>}</div><a className="slipstream-calendar" href="/dashboard?view=calendar">{t('Find your next call')}<ArrowUpRight size={16}/></a></div><p className="slipstream-hint">{t('Drag to explore')}</p><p className="sr-only" aria-live="polite">{t(sessions[active].name)} {t(sessions[active].caption)}</p></section>
}
