"use client";
import {useTranslation} from "@/components/language-provider";
import {useState} from 'react';
import {ArrowUpRight,Menu} from 'lucide-react';
import {LanguageSwitcher} from '@/components/language-provider';
import {Brand,Socials} from '@/components/brand';
import {Sheet,SheetContent,SheetTrigger,SheetTitle,SheetDescription} from '@/components/ui/sheet';
export function SiteHeader({active=''}:{active?:string}){const {t,locale}=useTranslation();const[open,setOpen]=useState(false);const links=[{href:'/protocol',label:'The protocol',id:'protocol'},{href:'/technology',label:'The technology',id:'technology'},{href:'/auctions',label:'The rhythm',id:'auctions'},{href:'/vision',label:'The vision',id:'vision'}];return <header className="site-header"><Brand/><nav aria-label={t("Main navigation")}>{t(links.map(l=><a key={l.id} href={l.href} aria-current={active===l.id?'page':undefined}>{t(l.label)}</a>))}<LanguageSwitcher/><a href="/dashboard" className="nav-launch">{t("Enter app ")}<ArrowUpRight size={16}/></a><Sheet open={open} onOpenChange={setOpen}><SheetTrigger asChild><button className="mobile-menu-toggle" aria-label={t("Open navigation")}><Menu size={21}/></button></SheetTrigger><SheetContent className="mobile-site-menu"><SheetTitle>{t("Luminary")}</SheetTitle><SheetDescription>{t("Private orders. Public conviction.")}</SheetDescription><a href="/" onClick={()=>setOpen(false)}>{t("Home")}</a>{t(links.map(l=><a key={l.id} href={l.href} onClick={()=>setOpen(false)}>{t(l.label)} <ArrowUpRight size={20}/></a>))}<a href="/dashboard" className="primary-action">{t("Enter the auction ")}<ArrowUpRight size={18}/></a><Socials/></SheetContent></Sheet></nav></header>}
export function SiteFooter(){const {t,locale}=useTranslation();return <footer className="site-footer"><div className="footer-top"><Brand/><p>{t("The closing auction")}<br/>{t("for tokenized stocks.")}</p><Socials/></div><div className="footer-directory"><div><span>{t("EXPLORE")}</span><a href="/protocol">{t("The protocol ")}<ArrowUpRight size={13}/></a><a href="/technology">{t("The technology ")}<ArrowUpRight size={13}/></a><a href="/auctions">{t("The rhythm ")}<ArrowUpRight size={13}/></a><a href="/vision">{t("The vision ")}<ArrowUpRight size={13}/></a><a href="/dashboard">{t("Auction terminal ")}<ArrowUpRight size={13}/></a></div><div><span>{t("LEGAL / DRAFTS")}</span><a href="/legal/terms">{t("Terms of use ")}<ArrowUpRight size={13}/></a><a href="/legal/privacy">{t("Privacy notice ")}<ArrowUpRight size={13}/></a><a href="/legal/risks">{t("Risk & eligibility ")}<ArrowUpRight size={13}/></a></div><p>{t("Private before the call.")}<br/>{t("Verifiable after it.")}<br/><span>{t("Built on Robinhood Chain.")}</span></p></div><div className="footer-wordmark calligraphy" aria-hidden="true">{t("Luminary")}</div><div className="footer-bottom"><span>{t("© ")}{t(new Date().getFullYear())}{t(" LUMINARY")}</span><span>{t("BUILT ON ROBINHOOD CHAIN")}</span><a href="/legal/risks">{t("No real funds ")}<ArrowUpRight size={13}/></a></div></footer>}
