"use client";
import {useEffect,useRef,useState,type CSSProperties} from 'react';
import {ArrowDown,ArrowUpRight} from 'lucide-react';
import {useTranslation} from '@/components/language-provider';
import {cascadeConfig,cardPose,clamp} from '@/lib/cascade-motion';
const cards=[
 {title:'Index rebalances',tag:'Liquidity',image:'landscape',position:'35% 50%',text:'Concentrate rebalance flow into one private closing auction.'},
 {title:'Issuer auctions',tag:'Launches',image:'torii-tides',position:'40% 50%',text:'A sealed opening print for tokenized-stock and ETF issuers.'},
 {title:'Calendar + prints',tag:'Data',image:'swallow-orbits',position:'25% 50%',text:'A shared reference close for terminals, agents and indices.'},
 {title:'The Arc lane',tag:'Settlement',image:'mountain-tide',position:'50% 60%',text:'A planned USYC settlement lane and StableFX-anchored FX calls.'},
 {title:'Agent mandates',tag:'Automation',image:'dragon-phoenix',position:'80% 50%',text:'Bounded mandates that bring sealed intent to scheduled calls.'},
 {title:'Settlement references',tag:'The horizon',image:'vision-waterfall',position:'50% 50%',text:'Trusted prints could support future onchain equity derivatives.'},
];
export default function VisionCascade({id='chapter'}:{id?:string}){
 const{t}=useTranslation();const section=useRef<HTMLElement>(null),stage=useRef<HTMLDivElement>(null),progress=useRef(0),reduced=useRef(false);const[active,setActive]=useState(0);
 useEffect(()=>{const el=section.current,pane=stage.current;if(!el||!pane)return;const media=matchMedia('(prefers-reduced-motion: reduce)');const nodes=[...el.querySelectorAll<HTMLElement>('.cascade-card')];let height=320,frame=0,visible=false,previous=-1;
 const render=()=>{frame=0;if(!visible||reduced.current)return;const nav=innerWidth<700?74:88,vh=innerHeight-nav,travel=Math.max(1,el.offsetHeight-vh),target=clamp((nav-el.getBoundingClientRect().top)/travel)*(cards.length-1);progress.current+=(target-progress.current)*cascadeConfig.ease;if(Math.abs(target-progress.current)<.0005)progress.current=target;nodes.forEach((card,i)=>{const pose=cardPose(i-progress.current,height);card.style.transform=pose.transform;card.style.opacity=String(pose.opacity);card.style.zIndex=String(pose.zIndex);card.style.setProperty('--sheen',String(pose['--sheen']))});el.style.setProperty('--cascade-progress',String(progress.current/(cards.length-1)));const next=clamp(Math.round(progress.current),0,cards.length-1);if(next!==previous){previous=next;setActive(next)}if(Math.abs(target-progress.current)>.0001)frame=requestAnimationFrame(render)};
 const request=()=>{if(!frame&&visible&&!reduced.current)frame=requestAnimationFrame(render)};
 const layout=()=>{reduced.current=media.matches;el.dataset.reduced=String(media.matches);if(media.matches){el.style.height='auto';nodes.forEach(card=>{card.style.transform='';card.style.opacity='';card.style.zIndex=''});cancelAnimationFrame(frame);frame=0;return}const nav=innerWidth<700?74:88,vh=innerHeight-nav,wide=innerWidth>880;let width=clamp(innerWidth*cascadeConfig.cardVW,cascadeConfig.cardMin,cascadeConfig.cardMax);height=Math.min(width*cascadeConfig.aspect,vh*(wide?.5:.40));width=height/cascadeConfig.aspect;pane.style.setProperty('--cw',`${width}px`);pane.style.setProperty('--ch',`${height}px`);pane.style.setProperty('--perspective',`${Math.max(1200,Math.min(innerWidth,vh)*2.5)}px`);el.style.height=`${vh+(cards.length-1)*innerHeight*cascadeConfig.perCardVh/100}px`;request()};
 const observer=new IntersectionObserver(([entry])=>{visible=entry.isIntersecting;if(visible)request();else{cancelAnimationFrame(frame);frame=0}},{rootMargin:'100px'});observer.observe(el);layout();window.addEventListener('scroll',request,{passive:true});window.addEventListener('resize',layout);media.addEventListener('change',layout);return()=>{cancelAnimationFrame(frame);observer.disconnect();window.removeEventListener('scroll',request);window.removeEventListener('resize',layout);media.removeEventListener('change',layout)};
 },[]);
 function go(index:number){const el=section.current;if(!el)return;const next=clamp(index,0,cards.length-1);if(reduced.current){el.querySelectorAll('.cascade-card')[next]?.scrollIntoView({behavior:'auto',block:'center'});return}const nav=innerWidth<700?74:88;window.scrollTo({top:window.scrollY+el.getBoundingClientRect().top-nav+(el.offsetHeight-(innerHeight-nav))*next/(cards.length-1),behavior:'smooth'})}
 return <section ref={section} id={id} className="vision-cascade" aria-label={t('04 / THE NEXT CHAPTER')}><div className="cascade-sticky"><div className="cascade-topline"><span>{t('04 / THE NEXT CHAPTER')}</span><span>{t('PLANNED ROADMAP · NOT LIVE FEATURES')}</span></div><div className="cascade-copy"><p className="eyebrow">{t('A FOUNDATION FOR MORE')}</p><h2>{t('Build.')}<br/><em className="calligraphy">{t('Expand.')}</em></h2><p>{t('Begin with a useful daily auction. Grow toward issuer launches, rebalance flows and a public calendar and print feed. Expansion follows real usage.')}</p><button className="cascade-next" onClick={()=>go(active===cards.length-1?0:active+1)}>{t(active===cards.length-1?'Explore again':'Explore the next chapter')}<ArrowDown size={17}/></button><a href="#roadmap-details">{t('Read the full roadmap')}<ArrowUpRight size={14}/></a></div><div ref={stage} className="cascade-stage" aria-hidden="true"><div className="cascade-deck">{cards.map((c,i)=><article key={c.title} className="cascade-card" style={cardPose(i,320) as CSSProperties}><div className="cascade-card-face"><img src={`/art/${c.image}.webp`} style={{objectPosition:c.position}} alt="" draggable={false} loading="eager"/><div className="cascade-card-scrim"/><div className="cascade-card-body"><div className="cascade-card-top"><span>{String(i+1).padStart(2,'0')} / 06</span><span>{t(c.tag)}</span></div><div><p className="eyebrow">{t('PLANNED')}</p><h3>{t(c.title)}</h3><p>{t(c.text)}</p></div></div></div></article>)}</div></div><nav className="cascade-rail" aria-label={t('Roadmap chapters')} onKeyDown={e=>{if(e.key==='ArrowRight'||e.key==='ArrowLeft'){e.preventDefault();go(active+(e.key==='ArrowRight'?1:-1))}}}><div><strong>{String(active+1).padStart(2,'0')}</strong><span>/ 06</span></div><div className="cascade-rail-track"><div className="cascade-rail-fill"/>{cards.map((c,i)=><button key={c.title} style={{top:`${i/(cards.length-1)*100}%`}} aria-current={active===i?'step':undefined} aria-label={`${String(i+1).padStart(2,'0')} · ${t(c.title)}`} onClick={()=>go(i)}><span/></button>)}</div><span className="cascade-rail-label">{t(cards[active].title)}</span></nav><p className="sr-only" aria-live="polite">{t(cards[active].title)}. {t(cards[active].text)}</p></div></section>
}
