/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuctionsRouteImport } from './routes/auctions'
import { Route as DashboardRouteImport } from './routes/dashboard'
import { Route as ProtocolRouteImport } from './routes/protocol'
import { Route as TechnologyRouteImport } from './routes/technology'
import { Route as VisionRouteImport } from './routes/vision'
import { Route as LegalPrivacyRouteImport } from './routes/legal/privacy'
import { Route as LegalRisksRouteImport } from './routes/legal/risks'
import { Route as LegalTermsRouteImport } from './routes/legal/terms'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuctionsRoute = AuctionsRouteImport.update({
  id: '/auctions',
  path: '/auctions',
  getParentRoute: () => rootRouteImport,
} as any)
const DashboardRoute = DashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => rootRouteImport,
} as any)
const ProtocolRoute = ProtocolRouteImport.update({
  id: '/protocol',
  path: '/protocol',
  getParentRoute: () => rootRouteImport,
} as any)
const TechnologyRoute = TechnologyRouteImport.update({
  id: '/technology',
  path: '/technology',
  getParentRoute: () => rootRouteImport,
} as any)
const VisionRoute = VisionRouteImport.update({
  id: '/vision',
  path: '/vision',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalPrivacyRoute = LegalPrivacyRouteImport.update({
  id: '/legal/privacy',
  path: '/legal/privacy',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalRisksRoute = LegalRisksRouteImport.update({
  id: '/legal/risks',
  path: '/legal/risks',
  getParentRoute: () => rootRouteImport,
} as any)
const LegalTermsRoute = LegalTermsRouteImport.update({
  id: '/legal/terms',
  path: '/legal/terms',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auctions': typeof AuctionsRoute
  '/dashboard': typeof DashboardRoute
  '/protocol': typeof ProtocolRoute
  '/technology': typeof TechnologyRoute
  '/vision': typeof VisionRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/risks': typeof LegalRisksRoute
  '/legal/terms': typeof LegalTermsRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auctions': typeof AuctionsRoute
  '/dashboard': typeof DashboardRoute
  '/protocol': typeof ProtocolRoute
  '/technology': typeof TechnologyRoute
  '/vision': typeof VisionRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/risks': typeof LegalRisksRoute
  '/legal/terms': typeof LegalTermsRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/auctions': typeof AuctionsRoute
  '/dashboard': typeof DashboardRoute
  '/protocol': typeof ProtocolRoute
  '/technology': typeof TechnologyRoute
  '/vision': typeof VisionRoute
  '/legal/privacy': typeof LegalPrivacyRoute
  '/legal/risks': typeof LegalRisksRoute
  '/legal/terms': typeof LegalTermsRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auctions'
    | '/dashboard'
    | '/protocol'
    | '/technology'
    | '/vision'
    | '/legal/privacy'
    | '/legal/risks'
    | '/legal/terms'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auctions'
    | '/dashboard'
    | '/protocol'
    | '/technology'
    | '/vision'
    | '/legal/privacy'
    | '/legal/risks'
    | '/legal/terms'
  id:
    | '__root__'
    | '/'
    | '/auctions'
    | '/dashboard'
    | '/protocol'
    | '/technology'
    | '/vision'
    | '/legal/privacy'
    | '/legal/risks'
    | '/legal/terms'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuctionsRoute: typeof AuctionsRoute
  DashboardRoute: typeof DashboardRoute
  ProtocolRoute: typeof ProtocolRoute
  TechnologyRoute: typeof TechnologyRoute
  VisionRoute: typeof VisionRoute
  LegalPrivacyRoute: typeof LegalPrivacyRoute
  LegalRisksRoute: typeof LegalRisksRoute
  LegalTermsRoute: typeof LegalTermsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auctions': {
      id: '/auctions'
      path: '/auctions'
      fullPath: '/auctions'
      preLoaderRoute: typeof AuctionsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/dashboard': {
      id: '/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof DashboardRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/protocol': {
      id: '/protocol'
      path: '/protocol'
      fullPath: '/protocol'
      preLoaderRoute: typeof ProtocolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/technology': {
      id: '/technology'
      path: '/technology'
      fullPath: '/technology'
      preLoaderRoute: typeof TechnologyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vision': {
      id: '/vision'
      path: '/vision'
      fullPath: '/vision'
      preLoaderRoute: typeof VisionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/privacy': {
      id: '/legal/privacy'
      path: '/legal/privacy'
      fullPath: '/legal/privacy'
      preLoaderRoute: typeof LegalPrivacyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/risks': {
      id: '/legal/risks'
      path: '/legal/risks'
      fullPath: '/legal/risks'
      preLoaderRoute: typeof LegalRisksRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/legal/terms': {
      id: '/legal/terms'
      path: '/legal/terms'
      fullPath: '/legal/terms'
      preLoaderRoute: typeof LegalTermsRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuctionsRoute: AuctionsRoute,
  DashboardRoute: DashboardRoute,
  ProtocolRoute: ProtocolRoute,
  TechnologyRoute: TechnologyRoute,
  VisionRoute: VisionRoute,
  LegalPrivacyRoute: LegalPrivacyRoute,
  LegalRisksRoute: LegalRisksRoute,
  LegalTermsRoute: LegalTermsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
